services:
  - name: household-services-web
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      flask db upgrade && flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: household-services-db
          property: connectionString
      - key: CELERY_BROKER_URL
        value: redis://household-services-redis:6379/1
      - key: CELERY_RESULT_BACKEND
        value: redis://household-services-redis:6379/2
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromGroup: household
      - key: SECURITY_PASSWORD_SALT
        fromGroup: household
      - key: GOOGLE_CHAT_WEBHOOK_URL
        fromGroup: household
    plan: free
    autoDeploy: true

  - name: household-services-redis
    type: redis
    plan: free

  - name: household-services-worker
    type: worker
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      celery -A app:celery_app worker --loglevel=info
    envVars:
      - key: DATABASE_URL
         fromGroup: household
      - key: CELERY_BROKER_URL
        value: redis://household-services-redis:6379/1
      - key: CELERY_RESULT_BACKEND
        value: redis://household-services-redis:6379/2
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromGroup: household
      - key: SECURITY_PASSWORD_SALT
        fromGroup: household
      - key: GOOGLE_CHAT_WEBHOOK_URL
        fromGroup: household

  - name: household-services-scheduler
    type: worker
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      celery -A app:celery_app beat --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromGroup: household
      - key: CELERY_BROKER_URL
        fromGroup: household
      - key: CELERY_RESULT_BACKEND
        fromGroup: household
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromGroup: household
      - key: SECURITY_PASSWORD_SALT
        fromGroup: household
      - key: GOOGLE_CHAT_WEBHOOK_URL
        fromGroup: household

  - name: household-services-db
    type: postgres
    plan: free
    properties:
      databaseName: household_services
      user: household_services_user
      password: household_services_password
