services:
  # Web service (Flask app)
  - name: household-services-web
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      flask db upgrade && python seed.py && flask run --host=0.0.0.0 --port=$PORT
    envVars:
      - fromGroup: household
    plan: free
    autoDeploy: true

  # Worker service (Celery worker)
  - name: household-services-worker
    type: worker
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      celery -A app:celery_app worker --loglevel=info
    envVars:
      - fromGroup: household

  # Scheduler service (Celery Beat)
  - name: household-services-scheduler
    type: worker
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      celery -A app:celery_app beat --loglevel=info
    envVars:
      - fromGroup: household
